### ISSUE TITLE
features missing to support iroh

### ISSUE THREAD

**Issue by dignifiedquire** [google/zerocopy#1093]
**What is the name of your project?**
iroh

**Please provide a link to your project (GitHub repository, crates.io page, etc).**
https://github.com/n0-computer/iroh

**What features would you like from zerocopy?**

Deriving/implementing `FromBytes` and `AsBytes` for structs with trailing byte slices.

```
#[derive(Debug, Clone, PartialEq, Eq)] // Can't add FromBytes, AsBytes, FromZeroes here 
#[repr(C)]
pub struct RecordIdentifier<B: ByteSlice> {
    namespace: [u8; 32],
    author: [u8; 32],
    key: B,
}
```

This is to support reading these identifiers from [`redb`](https://docs.rs/redb).

**Comment by joshlf** [comment]
Thanks for the request!

We're currently implementing something that should support this in #29. You can try this out in our [latest 0.8 alpha release](https://docs.rs/zerocopy/0.8.0-alpha.7/zerocopy/trait.KnownLayout.html). In particular, add `#[derive(KnownLayout)]` to the top of your struct, and then APIs with a `KnownLayout` bound such as [`FromBytes::ref_from`](https://docs.rs/zerocopy/0.8.0-alpha.7/zerocopy/trait.FromBytes.html#method.ref_from) should be available to you.

Please note that this is under active development - we're still adding support for some APIs, and APIs are subject to changes (both changes to type signatures and name changes) before we stabilize and release 0.8. That said, we'd love for you to kick the tires and let us know if it works for you or if there are things we should change/add before we release 0.8!

**Comment by dignifiedquire** [comment]
I guess this feature is currently dependent on `std::mem::size_of_val_raw` :/

**Comment by dignifiedquire** [comment]
I wonder if a `nightly` flag could be added to `zerocopy` to allow for doing this when using a nightly compiler, as a stopgap until this gets stabilized.

**Comment by dignifiedquire** [comment]
For reference, here is a complete gist that I am using to test this out: https://gist.github.com/dignifiedquire/ea1219ba8de5c02904b2680844759864

**Comment by joshlf** [comment]
If you use `#[repr(C, packed)]`, then you can derive `IntoBytes` directly. [Here's an example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=76c52d72bacd01e558b2bbe5f243423c) from 0.7 (because that's what's available on the Rust Playground; note that `AsBytes` is only renamed to `IntoBytes` in 0.8):

```rust
use zerocopy::*;

#[derive(AsBytes)]
#[repr(C, packed)]
pub struct RecordIdentifier {
    namespace: [u8; 32],
    author: [u8; 32],
    key: [u8],
}

impl AsRef<[u8]> for RecordIdentifier {
    fn as_ref(&self) -> &[u8] {
        self.as_bytes()
    }
}
```

Basically what's happening here is that, without `repr(packed)`, the `IntoBytes` derive isn't smart enough to know that your type will never have padding (padding in DSTs is weird - the trailing padding is calculated dynamically as a function of the trailing slice length). In this particular case, `repr(packed)` doesn't actually change anything because none of your field types have alignment greater than 1 anyway, but it's a guarantee that the `IntoBytes` derive knows how to understand.

**Comment by dignifiedquire** [comment]
Perfect, works as I need it. Thanks a lot for the great support. Feel free to close or keep upon until 0.8 is released.

**Comment by joshlf** [comment]
Of course, np! I'm gonna close since this is already on our roadmap, but feel free to open a new issue if other things come up.
