### ISSUE TITLE
Support byte-order for enumerations

### ISSUE THREAD

**Issue by jtsylve** [google/zerocopy#1486]
In my use case, I read a lot of on-disk structures that might not be native to the system, so byte-order is important.  Now that 0.8 supports TryFromBytes for exhaustive enumerations, I want to use that feature to help with my parsing validation.  I can't seem to figure out how to properly handle specifying the byte-order of enumeration types.

For example, I might have a structure like this:

```rust
#[derive(Debug, KnownLayout, Immutable, IntoBytes, TryFromBytes, Clone, Copy)]
#[repr(u32)]
pub enum DataStoreVersion {
    /// Version 1 of the data store.
    V1 = 9,

    /// Version 2 of the data store.
    V2 = 10,
}

#[derive(Debug, KnownLayout, Immutable, IntoBytes, TryFromBytes]
#[repr(C, packed)]
pub struct DataStore {
    /// Version stored as a 4-byte little endian value
    pub Version: DataStoreVersion, // <-- How do I specify that this is LittleEndian?
    
    /// Some other little-endian field
    pub SomeOtherField: U32<LE>,
    
    // other fields...
}
```

Is there currently any way that I can either mark up the enumeration or structure to handle this use case?

**Comment by joshlf** [comment]
Unfortunately I believe that this is not possible natively with Rust. In particular, there's no way to tell Rust "represent this enum using little endian".

However, it appears that, since discriminants can be arbitrary `const` expressions, you can do the following:

```rust
#[derive(Debug, KnownLayout, Immutable, IntoBytes, TryFromBytes)]
#[repr(u32)]
pub enum DataStoreVersion {
    /// Version 1 of the data store.
    V1 = 9u32.to_le(),

    /// Version 2 of the data store.
    V2 = 10u32.to_le(),
}
```

I've confirmed that this at least compiles on our [latest alpha release](https://docs.rs/zerocopy/0.8.0-alpha.22/zerocopy/index.html).

Feel free to re-open if that doesn't do what you need or if you'd like more support for this pattern.
