### ISSUE TITLE
Any way to convert zerocopy Struct to tokio `bytes::Bytes`?

### ISSUE THREAD

**Issue by ileixe** [google/zerocopy#149]
Hi,

Our crates use tokio [bytes::Bytes](https://docs.rs/bytes/latest/bytes/struct.Bytes.html) and I'm trying to leverage zercopy Struct. To be specific.

```rust
use zerocopy::{AsBytes, FromBytes};

#[derive(FromBytes, AsBytes)]
#[repr(C)]
struct A(u32);

fn main() {
    let a = A(0);

    let b = Bytes::from(a.as_bytes());  # It's not working as `Bytes::from` requires `static lifetime.
}
``` 

As `bytes::Bytes` is one of the most popular implementation, I wonder there is any native way to use zerocopy avoiding copy.

Thanks.

**Comment by joshlf** [comment]
Looking at the `bytes::Bytes` API, I don't see any way to go from a `&[u8]` with non-static lifetime to a `Bytes`. It looks like `Bytes` can only be constructed from static slices or owned, heap-allocated objects (`Box<[u8]>`, `String`, etc). Since, in your example, `a` is allocated on the stack, there's no way to treat it as any of these heap-allocated types without explicitly copying the memory to the heap. If it were already on the heap, I could imagine zerocopy supporting a conversion like `Box<A> -> Box<[u8]>`, although we don't support that today. Conversions like that are tracked in #114.
