### ISSUE TITLE
Ignore PhantomData

### ISSUE THREAD

**Issue by qwandor** [google/zerocopy#1744]
This works:

```rust
#[derive(AsBytes, FromZeroes)]
#[repr(C)]
struct Foo {
  value: u32,
}
```

This doesn't, despite having the same layout:

```rust
#[derive(AsBytes, FromZeroes)]
#[repr(C)]
struct Foo<A> {
  value: u32,
  _phantom: PhantomData<A>,
}
```

Can this be fixed, by making zerocopy ignore `PhantomData` (or more generally, zero-sized fields)?

**Comment by jswrenn** [comment]
You can work around this limitation by marking `Foo` as `repr(transparent)`. For structs with multiple non-ZST fields, use `repr(C, packed)`.

**Comment by joshlf** [comment]
As a bit of background on why it's hard to support as written, our analysis doesn't have access to enough information to determine that `PhantomData` is zero-sized and that its alignment is not greater than `u32`'s alignment. Both of those are needed in order to be sure that `Foo<A>` doesn't have padding.

On 0.8, we come *closer* to supporting this. In particular, you can derive `IntoBytes` on a generic `#[repr(C)]` type so long as all field types implement `Unaligned`. That doesn't help in this case, but if you could remove `u32`'s alignment requirement, it'd work.

The long-term plan to support this is via [`TransmuteFrom`](https://doc.rust-lang.org/nightly/std/mem/trait.TransmuteFrom.html).

**Comment by qwandor** [comment]
Thanks for the quick reply! `#[repr(transparent)]` does indeed work in this case, I didn't realise that it was possible for structs with more than a single field. I've now come to a slightly more complex case where I can't seem to use `repr(transparent)` because I also need to specify alignment:

```rust
#[derive(AsBytes, FromZeroes)]
#[repr(C, align(4096))]
struct Bar<A> {
  entries: [Foo<A>; 1024],
}
```

Is there any way around this, or do I need to manually implement `AsBytes` in this case?

**Comment by joshlf** [comment]
If you can make `A` concrete, then we can support it - in that case, we are able to emit a compile-time check that the size of the outer type is equal to the sum of the sizes of its fields (which is equivalent to saying that there's no inter-field padding). But this check isn't possible when there are generic type parameters.

I can't think of any way we could support this as written unfortunately.

**Comment by jswrenn** [comment]
Hm, perhaps we could introduce `MaybeIntoBytes`, that does its padding check in each of its methods and errors with a PME.
