### ISSUE TITLE
Extension trait for Vec forwarding to extend_vec_zeroed/insert_vec_zeroed/new_vec_zeroed

### ISSUE THREAD

**Issue by peter-lyons-kehl** [google/zerocopy#2183]
Goal: An ergonomic alternative to `FromZeros::{extend_vec_zeroed, insert_vec_zeroed}` that would be called with `Vec<T>` as `&mut self` receiver. Then, for example:
  -  `u8s.extend_zeroed(additional)?;`
  -  `u8s.insert_zeroed(3, additional)?;`

Extra: A less ergonomic, but more (opinionated) "std/constructor-like/idiomatic" alternative to `FromZeros::new_vec_zeroed` that would be called with `Vec<T>` as `Self` type receiver. Then, for example:
  -  `let u8s = Vec::<u8>::new_zeroed(len)?;`
  - Maybe useful when refactoring existing code that has `Vec::<u8>::new()` or `Vec::<u8>::with_capacity(len)`. (Yes, `new()` and `with_capacity(...)` return empty vectors, but still similar.)

How: A (sealed) extension trait that would be blanket-implemented only for `Vec<T>`, forwarding the above three functions to their `FromZeros` couunterparts. The user imports that trait, and she/he can call the above functions.

https://github.com/peter-lyons-kehl/zerocopy-vec --> https://github.com/peter-lyons-kehl/zerocopy-vec/blob/main/src/lib.rs
- (Side note: Ignore that a few tests fail, that's a work-in-progress of a separate issue).

Curious about your opinion/tips/other ways...

If you'd like this to be in `zerocopy`, I'll happily create a pull request. Otherwise, and unless you disagree, I'd create a sister crate.

**Comment by jswrenn** [comment]
Hi Peter, thanks for the suggestion. As a rule, we avoid extension traits because they're SemVer hazards. If another trait is in scope with the same method name and the same receiver, Rust cannot automatically resolve which method to call. When the conflict occurs in your own code, it's easy enough to use the fully-qualified syntax. But when the conflict occurs in a dependency, working around the problem can be very frustrating. Zerocopy appears deep in the dependency trees of most of our users, so we need to be particularly mindful of this risk.

Pragmatically, we're also concerned with the maintenance surface area of this crate. When developing 0.7 into 0.8, we found we *repeatedly* forgot to make documentation and implementation improvements to the free functions `extend_vec_zeroed`, `insert_vec_zeroed`. Ultimately, we decided to move these free functions into the `FromZeros` trait, to co-locate them with the rest of the core API. Not only did this make maintenance easier for us, we felt it improved the organization of the library (at the expense of ergonomics), as all initialization and conversion functionality was now organized beneath the requisite trait.

For these reasons, I think we're unlikely to add extension traits at this time. On balance, the ergonomic costs are outweighed by the SemVer, documentation, and maintenance benefits, and it's easy enough for our customers to write their own extension traits that forward to `zerocopy`.

**Comment by peter-lyons-kehl** [comment]
Thank you Jack. I agree about the surface area.

In case the team ever considers extension traits again: I thought they'd cause conflicts only if the trait is imported. And, if the user imports with wildcards, like `use zerocopy::{*, error::*};`, we can prevent conflicts caused by new traits (or new anything) by putting new traits/functionality into new submodules.

Merry Christmas.
