### ISSUE TITLE
CI step "Set toolchain version" can fail without stopping CI job

### ISSUE THREAD

**Issue by joshlf** [google/zerocopy#225]
In [this CI job](https://github.com/google/zerocopy/actions/runs/5754097055/job/15598706930?pr=222), it appears that a network error causes issues with the "Set toolchain version" step, but the GitHub runner does not fail at that point. Instead, later steps are executed with bad data (namely, the `ZC_TOOLCHAIN` environment variable is set to an empty string), causing confusing errors.

I suspect that what's happening is that the shell script executed for that step has a bug that results in errors inside of `$(...)` to not respect the `set -e` at the top of the script.

**Comment by joshlf** [comment]
Hey @zoo868e, sounds good, thanks! Let me know if you have any questions at any point!

**Comment by zoo868e** [comment]
Hello @joshlf,

It seems that the issue is arising intermittently, possibly due to a GitHub action facing difficulties in fetching dependencies during the execution of `cargo metadata`. After replicating the problem, I managed to execute all the tasks successfully, including a re-run of the previously failed job.

Therefore, I'm interested to know if there is a reliable method to verify whether the issue has been resolved, given that it doesn't occur consistently.

The approach that comes to mind for me to assess the issue's current status is to run the CI process multiple times and hope that the problem shows up.

Thank you.
