### ISSUE TITLE
what's the plan for v0.8.0? 

### ISSUE THREAD

**Issue by ianzhaoyue** [google/zerocopy#765]
Hi,

Not sure if this the best way to ask this question, but I want to know what's the timeline for the release of v0.8.0? We are waiting for [this](https://github.com/google/zerocopy/issues/716) to be release with fix for RUSTSEC-2023-0074.

Thanks!

**Comment by joshlf** [comment]
We don't have a specific timeline - it will be released as soon as possible, but that could be a few months from now depending on how things go.

However, that bug is now fixed on all version trains. The most recent 0.7.x release doesn't contain the bug (and the same is true for all other version trains).
